### ISSUE TITLE
store.get() without parameters doesn't work

### ISSUE THREAD

**Issue by jardicc** [jonschlinkert/data-store#17]
store.get() without parameters doesn't work in version 3.0 but works in 1.0 
In documentation is example without parameters.

**Comment by sant123** [comment]
Exactly, it throws this error: 

```
assert.js:83
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: expected key to be a string
```

A workaround here is `store.data`. I think docs should be updated.

**Comment by dkebler** [comment]
@sant123  months later still a problem ... 

either support should be put back in or docs updated although IMO it be supported as was.  

Dev has been silent.  @jonschlinkert do you have time to do this?  Accepting PRs?

**Comment by jonschlinkert** [comment]
Why not just do ‘store.data’? 

Months later, and it still doesn’t make sense.

**Comment by jardicc** [comment]
I switched to the: https://www.npmjs.com/package/preferences This is really great module. Once you assign value then it saved by default and it looks like just like JS object. I believe it uses setters.

**Comment by jonschlinkert** [comment]
fixed by https://github.com/jonschlinkert/data-store/issues/17
