### ISSUE TITLE
TypeError: Class constructor Store cannot be invoked without 'new'

### ISSUE THREAD

**Issue by pimlie** [jonschlinkert/data-store#19]
If I include a store as follows I get a Type Error about the class constructor (node v8.12)
```js
const store = require('data-store')('my-store')
// TypeError: Class constructor Store cannot be invoked without 'new'

const Store = require('data-store')
const store = new Store('my-store')
// works
```

Maybe it would be best to export a function instead of the class?

```js
module.exports = function(name, options, defaults) {
  return new Store(name, options, defaults)
}
```

**Comment by iREDMe** [comment]
(I was just searching for persistent libs and came across this)

I believe you have to to enclose the `require('data-store')` with parenthesis, and put `new` before the `require` part

Example:
```js
new (require('e'))('heck')
```

**Comment by jonschlinkert** [comment]
This should be possible now, in v4.0. 

@iREDMe's suggestion will also work. Thanks @iREDMe!
