### ISSUE TITLE
has-own-deep instead of has-value

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/data-store#2]
Because `.has` won't return true when dot notation is used if `key` value is `null` or `undefined` value on the data store and that values are possible case for stores/DBs/etc.

**Comment by jonschlinkert** [comment]
that would be another method then, since `has` returns true if a value is truthy, `hasOwn` would return true if a key exists. want to do a pr to add `hasOwn`?

**Comment by tunnckoCore** [comment]
okey, i'll

**Comment by tunnckoCore** [comment]
closing, as per #3
