### ISSUE TITLE
store.set() key with dot dymbol

### ISSUE THREAD

**Issue by Yermi** [jonschlinkert/data-store#20]
hi,

i am trying to store with a key containing a dot mark, something like this:
`users.set('a.b', 'c')`

but in the store the key is separated, like this:
`  "a": {
    "b": "c"
  }`
can someone please explain me the right way to get my key not separated?

thankes

**Comment by jonschlinkert** [comment]
In case this helps anyone else, just escape the dot with backslashes, e.g. `a\\.b`
