### ISSUE TITLE
Inconsistency of undefined

### ISSUE THREAD

**Issue by Flubberlutsch** [jonschlinkert/data-store#21]
Given the case I call store.set with no value, the key-value pair will be removed from the json file but will remain as key-undefined in memory. Hence Object.keys remains to contain the key only until the file is being read again.
It would be nice to have this be consistent instead.

**Comment by jonschlinkert** [comment]
> It would be nice to have this be consistent instead.

I can see how it would make sense to support this. I'll push up a patch. 

In the meantime, for anyone who stops by:

1. Use `store.del('foo')` to delete the property completely, or
1. Do `store.set('foo', null)` if you want to keep the property and not have it removed by `JSON.stringify()`.
