### ISSUE TITLE
Delete object inside array

### ISSUE THREAD

**Issue by debelop13** [jonschlinkert/data-store#22]
Hi

I want to delete only one object of the array, like this :

{ bars: [ {bar: 'baz', bar2: 'baz2', }  ] }

It is possible?

Thanks!

**Comment by doowb** [comment]
You cannot directly delete the object using the `.del` method, but you can use `.get` and `.set` to remove the object from the array. The following code assumes that you will be finding the object based on the `bar` property:

```js
// initialize the store and data
const store = new DataStore();
store.set('bars', [{ bar: 'baz', bar2: 'baz2' }]);

// get the array
let arr = store.get('bars');

// use filter to remove the item
arr = arr.filter(item => item.bar !== 'baz');

// set the item back in the store
store.set('bars', arr);
```
