### ISSUE TITLE
Create optional lock file for use of the data-store by external process

### ISSUE THREAD

**Issue by cblauvelt** [jonschlinkert/data-store#27]
I would like the option to create a lock file when the data-store is being synchronized. I understand this can cause slow-down so it would be off by default.

**Comment by cblauvelt** [comment]
I am willing to provide a patch but wanted to know if you would be open to accepting it and if adding lockfile from https://github.com/npm/lockfile would be acceptable to implement.

**Comment by jonschlinkert** [comment]
You can use lockfiles in your own libraries to lock the version of data-store to whatever you want. However, for reasons that will take more time to explain than I have right now, we don't use lockfiles in our libraries. Lockfiles prevent semver from doing it's job, and our experience has been that - between semver and lockfiles - semver is the lesser of two evils.

**Comment by doowb** [comment]
@jonschlinkert I don't think @cblauvelt was talking about a package lock file, but a lockfile to only allow a single process to access the file at a time.

**Comment by cblauvelt** [comment]
@doowb I was a little confused bye the response and I was trying to figure out how semver would prevent another process from accessing the file while it was being written. @jonschlinkert I am trying to prevent an external process from reading the data-store while the file is being written and I am not trying to implement a package lock file such as that used by npm or yarn.

**Comment by jonschlinkert** [comment]
Oh like a mutex?

**Comment by jonschlinkert** [comment]
Got it. Yeah I think you’re looking for atomic writes. Or we can use a mutex, or a combination of those.

**Comment by cblauvelt** [comment]
Exactly like a mutex.
