### ISSUE TITLE
Retrieving data-store

### ISSUE THREAD

**Issue by OlutobiOgunsola** [jonschlinkert/data-store#31]
Hi, is there a feature that allows you retrieve data set into the store from another js file? Or can you only read data set into the store from the same file.

**Comment by doowb** [comment]
The store data is saved in a json file so as long as both js files use the same json file, then they can both read the data.

If file one sets the data, then file two will need to use the `store.load()` method to reload the file into memory. `data-store` does not handle managing multiple file access to the json file.
