### ISSUE TITLE
decreated isObject

### ISSUE THREAD

**Issue by dkebler** [jonschlinkert/data-store#33]
Probably want to use alternative at below as this is deprecated since 4.0

https://github.com/jonschlinkert/data-store/blob/bd96ee906b7c0220df973914159d634a12033b32/index.js#L89

https://nodejs.org/api/util.html#util_util_isobject_object

Looks like you want a plain Object checker?   Like ironically your package

https://github.com/jonschlinkert/is-plain-object

**Comment by doowb** [comment]
That `isObject` comes from a local `utils` file, not from the built-in `util` module. This is fine.
