### ISSUE TITLE
NPM owner

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/data-store#34]
@jonschlinkert will you add me as an NPM owner so I can publish `4.1.0`. Thanks!

**Comment by derrell** [comment]
At present, the npm-published code does not appear to match what's in github. The changes in #29, at least, have not yet been published. Would greatly appreciate having latest code published! Thanks. @jonschlinkert @doowb

**Comment by jonschlinkert** [comment]
@doowb done, sorry I didn't see this earlier

**Comment by doowb** [comment]
Thanks!
