### ISSUE TITLE
Data-store wont save anything.

### ISSUE THREAD

**Issue by ghost** [jonschlinkert/data-store#40]
I used data-store for a while now, and it worked well until i tried to store something from another folder, it just wont save no matter if i use .load() or .save(), the thing is sometimes it saves sometimes it doesn't and i checked its not because of my code. Ive double checked, the path is correct

**Comment by doowb** [comment]
@BananaSplit2213 do you have example of your code using `data-store`?
Also, can you provide more information, like which version of Node.js you're using and your OS?

**Comment by ghost** [comment]
Hey, i already fixed this so im here to close it and also to explain how. I defined store in another file and used module.exports and require to get it.

Example:
storage.js
```
let datastore = require ('data-store');
module.exports = {
store: new datastore({path: './foo.json});
}
```
any other file where i use it
```
let storage = require ('storage.js');
storage.store.get(key);
```
