### ISSUE TITLE
default cwd to be not `~/data-store` but hidden `~/.data-store`?

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/data-store#7]

**Comment by jonschlinkert** [comment]
why?

**Comment by jonschlinkert** [comment]
sorry, meaning is there a disadvantage in having the data-store _not_ hidden?

**Comment by tunnckoCore** [comment]
In both case there's no disadvantage, but i think such things is more correct to be hidden. Because actually user don't have job there, or okey maybe in rare case he will want to update it manually, not through api. But the main idea of this store is to store, second is to be controled/modified by API.

**Comment by jonschlinkert** [comment]
always good to learn how other devs prefer their setup. I don't mind changing it

**Comment by tunnckoCore** [comment]
closing, https://github.com/jonschlinkert/data-store/commit/9c14af15fb262c1dd960a154ffbba53475be1290
